version: '3.8'
services:
  db:
    image: mongo:6.0.5
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ium
volumes:
  db-data:
